### ISSUE TITLE
A quicker way

### ISSUE THREAD

**Issue by cmprmsd** [Peco602/findwall#2]
Nice idea, but you can achieve the same with `tcpdump host souceip` on the VPS side and "nmap -p- vpsip` on the other side. 
Nmap does outperform most manual python scripts. 
Also with tcpdump you will not need to open each port on after the other. :)

Do you plan on changing this behavior? 
You could easily also create one listener and redirect all ports to this listener with iptables.

**Comment by Peco602** [comment]
Hello,

I like your proposal. I will evaluate it for the future.

Anyway, my idea was to keep it as simple as possible by performing all the processing locally and just asking the VPS to open a port. Moreover, my script currently works also without root permissions (for ports above 1024) while for tcpdump they would be mandatory.

**Comment by cmprmsd** [comment]
That's right. Another thing I noticed is that most corporate local networks won't allow for outgoing SSH. 
Buy the purpose of this tool is mostly for private usage I guess? :)

If SSH is not available you could also scan the host allports.exposed. This is limited to TCP though. 😊

**Comment by Peco602** [comment]
Another reason I discarded the nmap approach was to avoid any detection/limitation due to the suspicious traffic (and also its higher rate). That could impact the analysis.

I can also evaluate the possibility to add a random delay between each connection to decrease the probability to be detected.

I also added the possibility to change the SSH port to whatever you want.
